---
label: Post
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- type: file
  name: cover
  label: Cover
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: ''
pages:
- fa/_posts/news/2019-06-09-news-3.md
- fa/_posts/blog/2019-02-11-blog-post-2.md
- fa/_posts/blog/2019-02-10-blog-post-1.md
