---
label: Post
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- type: file
  name: cover
  label: cover
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: ''
- name: author
  label: Author
  type: text
  hidden: false
  default: bineshafza
- type: select
  name: layout
  config:
    source:
      type: simple
    required: true
    options:
    - post
    - post-ltr
  label: Post Language
  description: Select post language to define text-direction.
  default: post-ltr
pages:
- _posts/articles/Other/michel-de-montaigne.md
- _posts/articles/Other/cultural-mining.md
- _data/homepage.yml
- _posts/articles/Other/the-real-st-valentine-was-no-patron-of-love.md
- _posts/multimedia/quotes/2019-01-14-quote-of-the-day.md
- _posts/articles/Other/2019-02-10-یادگیری-خود-راهبر-یک-فرآیند-چهار-مرحله‌ای.md
- _posts/multimedia/quotes/2019-01-22-quote-of-the-day.md
- _posts/news/2019-01-19-ماک-آیلتس.md
- _posts/courses/2019-01-10-french-language.md
