---
label: Post
hide_body: false
fields:
  - name: title
    label: Title
    type: text
    hidden: false
    default: ""
  - name: date
    label: Date
    type: datetime
    hidden: false
    default: ""
  - type: file
    name: cover
    label: cover
    default: ""
  - name: tags
    label: Tags
    type: tag_list
    hidden: false
    default: ""
  - name: author
    label: Author
    type: text
    hidden: false
    default: ofoghmehr
  - type: select
    name: layout
    config:
      source:
        type: simple
      required: true
      options:
        - post
        - post-ltr
    label: Post Language
    description: Select post language to define text-direction.
    default: post-ltr
pages:
  - _data/homepage.yml
