---
label: Settings
hide_body: true
fields:
- name: mockdate
  type: datetime
  label: Mock Exam
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- name: placementdate
  type: datetime
  label: Placement
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- name: banner
  type: boolean
  label: Banner
  default: false
- name: bannertext
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: BannerText
pages:
- _data/homepage.yml
